### ISSUE TITLE
Does not work on SSL error pages or in UI elements

### ISSUE THREAD

**Issue by thw26** [jscher2000/Ctrl-Shift-C-Should-Copy#1]
I attempted to copy using Ctrl+Shift+C from an SSL error page and the URL bar but the developer tools appeared upon trying. Not sure if this plugin is able to correct this behavior or not.

**Comment by jscher2000** [comment]
**Error Pages**

This script should be injected into and should run on all pages that aren't restricted. The built-in pages (such as connection error pages, PDF viewer, Reader View, etc.) are restricted and no extensions can inject scripts into them. Unfortunately, there is nothing I can do about that.

**URL bar**

The script can only override the keyboard shortcut when the cursor is in the page -- it is a content script. The extension API doesn't provide any way to repurpose built-in keyboard shortcuts when the cursor is outside the page.

**Startup Script Alternative**

If you need to globally deactivate a keyboard shortcut, you could consider using a startup script to delete the keybinding. I have a general background page on how these scripts work, and you could get specific help on the r/FirefoxCSS community:

* https://www.userchrome.org/what-is-userchrome-js.html
* https://www.reddit.com/r/FirefoxCSS/ 

Possibly the script could also reassign Ctrl+Shift+C to Copy, so it would be a complete solution.

**Comment by ghost** [comment]
> **Error Pages**
> 
> This script should be injected into and should run on all pages that aren't restricted. The built-in pages (such as connection error pages, PDF viewer, Reader View, etc.) are restricted and no extensions can inject scripts into them. Unfortunately, there is nothing I can do about that.

@jscher2000 Can you please update the readme? This may not be self-evident to most potential users.
