### ISSUE TITLE
README enhancement

### ISSUE THREAD

**Issue by KevinWhalen** [jscher2000/Ctrl-Shift-C-Should-Copy#3]
I would like to suggest including a link to a tool like <https://robwu.nl/crxviewer/> to show that when given the Firefox Add-on URL (<https://addons.mozilla.org/en-US/firefox/addon/ctrl-shift-c-should-copy/>), the tool will prove that the add-on only installs what the source code in this repository claims it will: two short, event listener functions.

P.S. Thanks for making this. Ctrl+Shift+C has been a frequent headache for years, and I did not want a large, invasive add-on. Could have sworn key-mapping use to be a standard feature in Firefox a decade ago.

**Comment by jscher2000** [comment]
Like this?

https://robwu.nl/crxviewer/?crx=https%3A%2F%2Faddons.mozilla.org%2Fen-US%2Ffirefox%2Faddon%2Fctrl-shift-c-should-copy%2F

**Comment by KevinWhalen** [comment]
Yup, exactly like that.

Having the link to the source code in the description is great but having the link to that viewer in addition, proves that what is packaged is the same as what is in the public source code.

**Comment by jscher2000** [comment]
Finally done. I think I'll add it on AMO, too. Why not?
